### ISSUE TITLE
Auth Register - failed to register but data still inserted

### ISSUE THREAD

**Issue by hanalaydrus** [devsummit/backend#100]
# Description
I once input `role` data as string (e.g: `attendee`), the register return `"success": false` but the username and email still inserted in the database.

<br />

# Type
- [x] bug

<br />

**Comment by caudaganesh** [comment]
@andy-shi88 I can't reproduce this issue, the role validation seems already work correctly and no string allowed for "role". Data not inserted to db if the payloads are invalid. 

But i found incorrect parameter for role_id at user service which probably caused this problem.

**Comment by andy-shi88** [comment]
I'll close this one.
