### ISSUE TITLE
API - Indomaret Payment

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#175]
# Description
expose new payment method:
- [x] indomaret.

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by ivanzaqqa** [comment]
Can i do this project?

**Comment by andy-shi88** [comment]
sure, @ivanzaqqa please remember to create new branch and reference your commit to this issue.

**Comment by ivanzaqqa** [comment]
oke, thanks very much mas
