### ISSUE TITLE
Hackaton Role

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#277]
# Description
User should be able to register as hackaton
- [ ] create new hackaton table 
- [ ] add new hackaton row if create user as hackaton (tweak existing code)
- [ ] Get, show and update hackaton (api)
- [ ] admin page hackaton 
- [ ] 2 more ticket for hackaton (seed) (need to think about the schema amount)

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by andy-shi88** [comment]
due to uncertain rule of hackaton system implementation, we'll need to delay this.

**Comment by caudaganesh** [comment]
okay -
