### ISSUE TITLE
Admin - Speaker Management

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#303]
# Description
With stage -> like sponsor

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by erdivartanovich** [comment]
on progress almost finish @ branch : https://github.com/devsummit/backend/tree/303-speaker-management

**Comment by erdivartanovich** [comment]
@caudaganesh work on a tweak part of this issue cc @andy-shi88
