### ISSUE TITLE
Expose Authorize User Endpoint

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#387]
# Description
expose an endpoint for authorizing user, this would be to make sure the one that taking the action is logged in user.
- if password is right return `meta.success: true`
return a response that user understand to know if they are logged in or not.

put it in `routes/auth`

<br />

# Type
- [ ] feature
- [ ] bug

<br />

**Comment by ivanzaqqa** [comment]
can i do and learn this?

**Comment by andy-shi88** [comment]
sure, @ivanzaqqa

**Comment by ivanzaqqa** [comment]
oke thanks, i'm happy to learn it
