### ISSUE TITLE
API - package management

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#436]
# Description
Create exhibitor (formerly booth) package management.

I should be able to add, edit, and delete package in which we'll need these information
- price
- quota
- name (package name)

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by andy-shi88** [comment]
for the price, use float instead of integer, @hafizhanindito

**Comment by hafizhanindito** [comment]
okay @andy-shi88
