### ISSUE TITLE
Send Redeem Code

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#504]
# Description
On exhibitor succeeded registered, system should have a proper way to notify and send their result to the exhibitor
- email
- fcm notification

<br />

# Type
- [ ] feature
- [x] tweak

<br />

**Comment by ivanzaqqa** [comment]
excuse me , can i doing this issue? @andy-shi88

**Comment by andy-shi88** [comment]
actually I'm taking this one @ivanzaqqa  I'll prepare you some thing else.
