### ISSUE TITLE
Log System

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#516]
# Description
Create log for the following action
- ticket order
- payment
- referal (in registration)
- claim ticket for referal_count
- user redeem their code for ticket (for exhibitor, user and hackaton)

let's make this a one service, and call them from anywhere.
time of log will be save on utc and 

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by andy-shi88** [comment]
we'll need this as soon as possible, let's work on it, you may need to create new table, which contains of (`id`, `description`, `created_at`)

**Comment by ivanzaqqa** [comment]
what table should i create? @andy-shi88
