### ISSUE TITLE
Speaker Field

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#62]
# Description
Speaker need more fields:
- [ ] job

and `summary` field will be separated into 2 field:
- [ ] summary - a short summary about the speaker
- [ ] information - this will include long story about the speaker

note: add new field in migrations

<br />

# Type
- [x] tweak

<br />

**Comment by andy-shi88** [comment]
@erdivartanovich  what do you think? do we just add more field on old migration? or add new migration? my personal preference would be just add more field in the old migration file. since we don't have data yet.

**Comment by erdivartanovich** [comment]
agree, 
ok i'll edit the migration
