### ISSUE TITLE
API - User Picture

### ISSUE THREAD

**Issue by andy-shi88** [devsummit/backend#73]
# Description
Create api to upload stage pictures.

<br />

# Type
- [x] feature
- [ ] bug

<br />

**Comment by caudaganesh** [comment]
@andy-shi88 i already finish this sir, should i make PR?
its already on the https://github.com/devsummit/backend/tree/73-API-user-picture

**Comment by andy-shi88** [comment]
@caudaganesh thanks, and yeah please do, I'll review it :+1:
