### ISSUE TITLE
Bug Apiary

### ISSUE THREAD

**Issue by rizalsidikp** [devsummit/backend#82]
# Description
found bug in structure data in `ticket_transfer_log` spec, the data should be like this 
![pasted image at 2017_08_10 06_16 pm](https://user-images.githubusercontent.com/28643942/29168331-a0d57492-7df8-11e7-9692-d9e43483a801.png)

<br />

# Type
- [x] bug

**Comment by andy-shi88** [comment]
thanks, you can work on it @rizalsidikp
